/*
 * This source file was generated by the Gradle 'init' task
 */
package parcial2;

import parcial2.Service.ApiFrases;

public class App {
    public static void main(String[] args) {
      
        ApiFrases.ejecutar();

    }
}

