/*
 * This source file was generated by the Gradle 'init' task
 */
package parcial2;

import parcial2.Model.Frase;

public class App {

    public static void main(String[] args) {


        Frase f1 = new Frase("HOLA");
        f1.showEncrypted();

        Frase f2 = new Frase("LIFENG ES GAY");
        f2.showEncrypted();


    }
}

